name: Daily Commit

on:
  schedule:
    - cron: '0 */4 * * *'   # ÐºÐ°Ð¶Ð´Ñ‹Ðµ 4 Ñ‡Ð°ÑÐ°
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Daily activity
        run: |
          echo "Daily activity on $(date)" >> activity.log
          git config user.name Anverte
          git config user.email anastasiakorobova6086@gmail.com
          git add activity.log
          git commit -m "ðŸ¤– Daily activity: $(date)"
          git push
